# Generated by Django 3.0.8 on 2020-07-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_account_app', '0003_auto_20200727_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(to='b_account_app.Tag'),
        ),
    ]
