# Generated by Django 3.0.8 on 2020-07-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_account_app', '0004_auto_20200727_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='b_account_app.Tag'),
        ),
    ]
