# Generated by Django 3.0.8 on 2020-08-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_account_app', '0005_auto_20200727_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'out for delivery'), ('Delivered', 'delivered')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
